import { easingNames } from "./easing.ts";
const num = { type: "number" },
  str = { type: "string" },
  bool = { type: "boolean" };
const positive = { type: "number", exclusiveMinimum: 0 };
const scalar = {
  anyOf: [num, { type: "string", minLength: 1, maxLength: 2000 }],
};
const name = { type: "string", pattern: "^[A-Za-z_][A-Za-z_0-9]*$" };
const ref = {
  type: "string",
  pattern: "^[A-Za-z_][A-Za-z_0-9]*\\.[A-Za-z_][A-Za-z_0-9]*$",
};
const color = { type: "string", pattern: "^#[0-9a-fA-F]{6}$" };
const array = (items: unknown, minItems = 0, maxItems = 10000) => ({
  type: "array",
  items,
  minItems,
  maxItems,
});
const coord = array(scalar, 1, 3),
  vec3 = array(num, 3, 3),
  range = array(num, 2, 2);
const obj = (properties: Record<string, unknown>, required: string[] = []) => ({
  type: "object",
  properties,
  required,
  additionalProperties: false,
});
const theme = obj({
  background: color,
  foreground: color,
  axes: color,
  grid: color,
  objectColors: array(color, 1, 100),
});
const style = obj({
  color,
  opacity: { ...num, minimum: 0, maximum: 1 },
  fillOpacity: { ...num, minimum: 0, maximum: 1 },
  strokeWidth: positive,
  pointSize: positive,
  fontSize: positive,
});
const drag = obj(
  {
    parameter: name,
    coordinate: { type: "integer", minimum: 0, maximum: 2 },
    min: num,
    max: num,
  },
  ["parameter"],
);
const samples = { type: "integer", minimum: 8, maximum: 2048 };
const matrixFields = {
  entries: array(array(scalar, 1, 32), 1, 32),
  cellWidth: positive,
  cellHeight: positive,
  decimals: { type: "integer", minimum: 0, maximum: 12 },
};
const graphFields = {
  vertices: array(name, 1, 128),
  edges: array(array(name, 2, 2), 0, 2048),
  layout: { enum: ["circle", "line"] },
  radius: positive,
  positions: {
    type: "object",
    propertyNames: name,
    additionalProperties: range,
  },
  labels: bool,
};
const imageSource = {
  type: "string",
  minLength: 1,
  maxLength: 2000000,
  pattern: "^(https?://|data:image/(png|jpeg|webp|gif);base64,|[^:]+$)",
};
export const objectFields = {
  ArcPolygon: { points: array(coord, 3, 128), angles: array(scalar, 3, 128) },
  AnimatedBoundary: {
    target: ref,
    period: positive,
    colors: array(color, 1, 32),
    timeWidth: { ...positive, maximum: 1 },
  },
  Union: { operands: array(ref, 2, 32) },
  Difference: { operands: array(ref, 2, 32) },
  Intersection: { operands: array(ref, 2, 32) },
  Exclusion: { operands: array(ref, 2, 32) },
  ImageMobject: { source: imageSource, width: scalar, height: scalar },
  ImageSequence: {
    sources: array(imageSource, 1, 128),
    fps: positive,
    start: { ...num, minimum: 0 },
    loop: bool,
    width: scalar,
    height: scalar,
  },
  Matrix: matrixFields,
  DecimalMatrix: matrixFields,
  IntegerMatrix: matrixFields,
  BarChart: {
    values: array(scalar, 1, 256),
    labels: array(str, 1, 256),
    barWidth: positive,
    gap: { ...num, minimum: 0 },
  },
  SampleSpace: {
    probabilities: array(positive, 1, 128),
    labels: array(str, 1, 128),
    width: positive,
    height: positive,
  },
  Graph: graphFields,
  DiGraph: graphFields,
  PictureInPicture: {
    space: name,
    x: num,
    y: num,
    width: positive,
    height: positive,
  },
  Point: { at: coord, drag },
  Line: { from: coord, to: coord },
  Arrow: { from: coord, to: coord },
  DoubleArrow: { from: coord, to: coord },
  DashedLine: {
    from: coord,
    to: coord,
    dashLength: scalar,
    dashRatio: { ...num, exclusiveMinimum: 0, exclusiveMaximum: 1 },
  },
  ArcBetweenPoints: { from: coord, to: coord, angle: scalar },
  CurvedArrow: { from: coord, to: coord, angle: scalar },
  CurvedDoubleArrow: { from: coord, to: coord, angle: scalar },
  Angle: {
    from: coord,
    vertex: coord,
    to: coord,
    radius: scalar,
    otherAngle: bool,
  },
  RightAngle: { from: coord, vertex: coord, to: coord, size: scalar },
  Triangle: { radius: scalar },
  SurroundingRectangle: { target: ref, padding: scalar },
  BackgroundRectangle: { target: ref, padding: scalar },
  Brace: {
    target: ref,
    side: { enum: ["left", "right", "top", "bottom"] },
    padding: scalar,
    depth: scalar,
  },
  Elbow: { width: scalar, angle: scalar },
  Annulus: { innerRadius: scalar, radius: scalar },
  AnnularSector: {
    innerRadius: scalar,
    radius: scalar,
    startAngle: scalar,
    angle: scalar,
  },
  RegularPolygram: {
    sides: { type: "integer", minimum: 3, maximum: 512 },
    step: { type: "integer", minimum: 1, maximum: 511 },
    radius: scalar,
  },
  ConvexHull: { points: array(coord, 3, 2048) },
  Polyhedron: {
    points: array(coord, 4, 2048),
    faces: array(array({ type: "integer", minimum: 0 }, 3, 128), 4, 4096),
  },
  ConvexHull3D: { points: array(coord, 4, 64) },
  Icosahedron: { radius: scalar },
  Dodecahedron: { radius: scalar },
  RoundedRectangle: { width: scalar, height: scalar, cornerRadius: scalar },
  ImplicitFunction: {
    expression: str,
    xRange: range,
    yRange: range,
    resolution: { type: "integer", minimum: 4, maximum: 256 },
  },
  ArrowVectorField: {
    expressions: coord,
    xRange: range,
    yRange: range,
    zRange: range,
    spacing: positive,
    lengthScale: scalar,
    maxLength: positive,
  },
  StreamLines: {
    expressions: coord,
    seeds: array(coord, 1, 256),
    step: positive,
    steps: { type: "integer", minimum: 1, maximum: 2048 },
  },
  TracedPath: {
    point: ref,
    start: { ...num, minimum: 0 },
    duration: positive,
    samples,
  },
  Polyline: { points: array(coord, 2) },
  Polygon: { points: array(coord, 3) },
  RegularPolygon: {
    sides: { type: "integer", minimum: 3, maximum: 512 },
    radius: scalar,
  },
  Star: {
    tips: { type: "integer", minimum: 2, maximum: 256 },
    radius: scalar,
    innerRadius: scalar,
  },
  Rectangle: { width: scalar, height: scalar },
  Square: { size: scalar },
  Circle: { radius: scalar },
  Ellipse: { radiusX: scalar, radiusY: scalar },
  Arc: { radius: scalar, startAngle: scalar, angle: scalar },
  Sector: { radius: scalar, startAngle: scalar, angle: scalar },
  Bezier: { points: array(coord, 4) },
  FunctionGraph: { expression: str, domain: range, samples },
  PolarGraph: { expression: str, domain: range, samples },
  ParametricCurve: { expressions: coord, domain: range, samples },
  PointOnCurve: { curve: ref, parameter: scalar, drag },
  Tangent: { curve: ref, parameter: scalar, length: scalar },
  Group: { children: array(ref, 1) },
  Text: { text: { ...str, maxLength: 10000 } },
  MathTex: { text: { ...str, maxLength: 10000 } },
  DecimalNumber: {
    value: scalar,
    decimals: { type: "integer", minimum: 0, maximum: 12 },
  },
  Sphere: { radius: scalar },
  Cube: { size: scalar },
  Cuboid: { width: scalar, height: scalar, depth: scalar },
  Cone: { radius: scalar, height: scalar },
  Cylinder: { radius: scalar, height: scalar },
  Torus: { radius: scalar, tubeRadius: scalar },
  Surface: {
    expressions: array(scalar, 3, 3),
    uRange: range,
    vRange: range,
    resolution: array({ type: "integer", minimum: 2, maximum: 128 }, 2, 2),
  },
};
const objectRequired: Record<string, string[]> = {
  ArcPolygon: ["points"],
  AnimatedBoundary: ["target"],
  Union: ["operands"],
  Difference: ["operands"],
  Intersection: ["operands"],
  Exclusion: ["operands"],
  ImageMobject: ["source"],
  ImageSequence: ["sources"],
  Matrix: ["entries"],
  DecimalMatrix: ["entries"],
  IntegerMatrix: ["entries"],
  BarChart: ["values"],
  SampleSpace: ["probabilities"],
  Graph: ["vertices", "edges"],
  DiGraph: ["vertices", "edges"],
  PictureInPicture: ["space", "x", "y", "width", "height"],
  Point: ["at"],
  Line: ["from", "to"],
  Arrow: ["from", "to"],
  DoubleArrow: ["from", "to"],
  DashedLine: ["from", "to"],
  ArcBetweenPoints: ["from", "to"],
  CurvedArrow: ["from", "to"],
  CurvedDoubleArrow: ["from", "to"],
  Angle: ["from", "vertex", "to"],
  RightAngle: ["from", "vertex", "to"],
  ImplicitFunction: ["expression", "xRange", "yRange"],
  ArrowVectorField: ["expressions", "xRange", "yRange"],
  StreamLines: ["expressions", "seeds"],
  TracedPath: ["point"],
  SurroundingRectangle: ["target"],
  BackgroundRectangle: ["target"],
  Brace: ["target"],
  ConvexHull: ["points"],
  ConvexHull3D: ["points"],
  Polyhedron: ["points", "faces"],
  RegularPolygram: ["sides", "step"],
  Polyline: ["points"],
  Polygon: ["points"],
  RegularPolygon: ["sides"],
  Star: ["tips"],
  Bezier: ["points"],
  FunctionGraph: ["expression"],
  PolarGraph: ["expression"],
  ParametricCurve: ["expressions"],
  PointOnCurve: ["curve", "parameter"],
  Tangent: ["curve", "parameter"],
  Group: ["children"],
  Text: ["text"],
  MathTex: ["text"],
  DecimalNumber: ["value"],
  Surface: ["expressions", "uRange", "vRange"],
};
export const eventFields = {
  Add: {},
  Create: {},
  Uncreate: {},
  FadeIn: {},
  FadeOut: {},
  MoveTo: { to: coord, from: coord },
  Shift: { by: coord },
  Rotate: { angle: num, axis: vec3 },
  Scale: { factor: positive },
  FadeToColor: { color },
  ApplyMatrix: { matrix: array(array(num, 1, 3), 1, 3) },
  MoveAlongPath: { path: ref },
  Indicate: { color, factor: positive },
  Wiggle: { angle: num },
  Homotopy: { expressions: coord },
  ComplexHomotopy: { expression: str },
  ApplyPointwiseFunction: { expressions: coord },
  PhaseFlow: {
    expressions: coord,
    steps: { type: "integer", minimum: 1, maximum: 512 },
    virtualTime: num,
  },
  Swap: { to: ref },
  FadeTransform: { to: ref },
  Restore: { at: { ...num, minimum: 0 } },
  Blink: { count: { type: "integer", minimum: 1, maximum: 100 } },
  ApplyWave: { amplitude: num, waves: positive, direction: vec3 },
  AddTextLetterByLetter: {},
  RemoveTextLetterByLetter: {},
  AddTextWordByWord: {},
  ShowIncreasingSubsets: {},
  ShowSubmobjectsOneByOne: {},
  GrowFromCenter: {},
  GrowArrow: {},
  GrowFromPoint: { point: coord },
  GrowFromEdge: {
    edge: { enum: ["left", "right", "top", "bottom", "front", "back"] },
  },
  SpinInFromNothing: { angle: num },
  DrawBorderThenFill: {},
  ShowPassingFlash: { timeWidth: { ...positive, maximum: 1 } },
  Flash: {
    color,
    radius: positive,
    lineLength: positive,
    numLines: { type: "integer", minimum: 2, maximum: 64 },
  },
  FocusOn: { color, radius: positive },
  Circumscribe: { color, padding: { ...num, minimum: 0 } },
  TransformFromCopy: { to: ref },
  Transform: { to: ref },
  ReplacementTransform: { to: ref },
};
const eventRequired: Record<string, string[]> = {
  Swap: ["to"],
  FadeTransform: ["to"],
  Homotopy: ["expressions"],
  ComplexHomotopy: ["expression"],
  ApplyPointwiseFunction: ["expressions"],
  PhaseFlow: ["expressions"],
  MoveTo: ["to"],
  Shift: ["by"],
  Rotate: ["angle"],
  Scale: ["factor"],
  FadeToColor: ["color"],
  ApplyMatrix: ["matrix"],
  MoveAlongPath: ["path"],
  TransformFromCopy: ["to"],
  Transform: ["to"],
  ReplacementTransform: ["to"],
  GrowFromPoint: ["point"],
  GrowFromEdge: ["edge"],
};
const timing = {
  start: { ...num, minimum: 0 },
  duration: { ...num, minimum: 0 },
};
const easing = { enum: easingNames };
export const supportedObjects = Object.freeze(
  Object.keys(objectFields) as (keyof typeof objectFields)[],
);
export const supportedEvents = Object.freeze([
  ...Object.keys(eventFields),
  "CyclicReplace",
  "AnimateParameter",
  "SwitchSpace",
  "CameraMove",
  "CameraOrbit",
  "CameraZoom",
  "CameraWindow",
  "ApplySpaceMatrix",
  "ApplyComplexFunction",
  "EventGroup",
  "Succession",
  "LaggedStart",
  "LaggedStartMap",
]);
export const supportedSpaces = Object.freeze([
  "axis1d",
  "plane2d",
  "polar2d",
  "space3d",
] as const);
export const pathObjects = [
  "ArcPolygon",
  "AnimatedBoundary",
  "Union",
  "Difference",
  "Intersection",
  "Exclusion",
  "SurroundingRectangle",
  "BackgroundRectangle",
  "Brace",
  "Elbow",
  "Annulus",
  "AnnularSector",
  "RegularPolygram",
  "ConvexHull",
  "DoubleArrow",
  "DashedLine",
  "ArcBetweenPoints",
  "CurvedArrow",
  "CurvedDoubleArrow",
  "Angle",
  "RightAngle",
  "Triangle",
  "RoundedRectangle",
  "ImplicitFunction",
  "ArrowVectorField",
  "StreamLines",
  "TracedPath",
  "Line",
  "Arrow",
  "Polyline",
  "Polygon",
  "RegularPolygon",
  "Star",
  "Rectangle",
  "Square",
  "Circle",
  "Ellipse",
  "Arc",
  "Sector",
  "Bezier",
  "FunctionGraph",
  "PolarGraph",
  "ParametricCurve",
  "Tangent",
];
export const sceneSchemaV1 = {
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "https://webnim-math.dev/schema/scene-v1.json",
  title: "Webnim declarative scene v1",
  ...obj(
    {
      version: { const: 1 },
      parameters: {
        type: "object",
        propertyNames: name,
        additionalProperties: num,
      },
      theme,
      spaces: array(
        obj(
          {
            name,
            type: { enum: supportedSpaces },
            theme,
            axes: { anyOf: [bool, array({ enum: ["x", "y", "z"] }, 0, 3)] },
            ticks: bool,
            grid: bool,
            camera: obj({
              center: vec3,
              position: vec3,
              scale: positive,
              projection: { enum: ["perspective", "orthographic"] },
            }),
            objects: array({ $ref: "#/definitions/object" }, 0, 2000),
          },
          ["name", "type", "objects"],
        ),
        1,
        32,
      ),
      events: array({ $ref: "#/definitions/event" }, 0, 2000),
      duration: { ...num, minimum: 0 },
    },
    ["version", "spaces"],
  ),
  definitions: {
    object: {
      discriminator: { propertyName: "type" },
      oneOf: Object.entries(objectFields).map(([type, fields]) =>
        obj(
          {
            id: name,
            caption: { type: "string", maxLength: 10000 },
            type: { const: type },
            position: coord,
            style,
            ...fields,
          },
          ["id", "type", ...(objectRequired[type] ?? [])],
        ),
      ),
    },
    event: {
      discriminator: { propertyName: "type" },
      oneOf: [
        ...Object.entries(eventFields).map(([type, fields]) =>
          obj(
            {
              type: { const: type },
              object: ref,
              ...timing,
              easing,
              ...fields,
            },
            ["type", "object", ...(eventRequired[type] ?? [])],
          ),
        ),
        obj(
          {
            type: { const: "CyclicReplace" },
            objects: { ...array(ref, 2, 128), uniqueItems: true },
            ...timing,
            easing,
          },
          ["type", "objects"],
        ),
        obj(
          {
            type: { const: "AnimateParameter" },
            parameter: name,
            to: num,
            from: num,
            ...timing,
            easing,
          },
          ["type", "parameter", "to"],
        ),
        obj(
          {
            type: { const: "ApplySpaceMatrix" },
            space: name,
            matrix: array(array(num, 1, 3), 1, 3),
            ...timing,
            easing,
          },
          ["type", "space", "matrix"],
        ),
        obj(
          {
            type: { const: "ApplyComplexFunction" },
            space: name,
            expression: str,
            ...timing,
            easing,
          },
          ["type", "space", "expression"],
        ),
        obj(
          {
            type: { const: "SwitchSpace" },
            space: name,
            transition: { enum: ["cut", "fade"] },
            ...timing,
          },
          ["type", "space"],
        ),
        obj(
          {
            type: { const: "CameraMove" },
            space: name,
            position: vec3,
            center: vec3,
            ...timing,
            easing,
          },
          ["type", "space", "position"],
        ),
        obj(
          {
            type: { const: "CameraOrbit" },
            space: name,
            angle: num,
            axis: vec3,
            ...timing,
            easing,
          },
          ["type", "space", "angle"],
        ),
        obj(
          {
            type: { const: "CameraZoom" },
            space: name,
            factor: positive,
            ...timing,
            easing,
          },
          ["type", "space", "factor"],
        ),
        obj(
          {
            type: { const: "CameraWindow" },
            space: name,
            x: range,
            y: range,
            ...timing,
            easing,
          },
          ["type", "space", "x"],
        ),
        obj(
          {
            type: { const: "LaggedStartMap" },
            objects: array(ref, 1, 2000),
            animation: {
              oneOf: Object.entries(eventFields).map(([type, fields]) =>
                obj(
                  {
                    type: { const: type },
                    duration: timing.duration,
                    easing,
                    ...fields,
                  },
                  ["type", ...(eventRequired[type] ?? [])],
                ),
              ),
            },
            ...timing,
            lagRatio: { ...num, minimum: 0 },
          },
          ["type", "objects", "animation"],
        ),
        ...["EventGroup", "Succession", "LaggedStart"].map((type) =>
          obj(
            {
              type: { const: type },
              ...timing,
              lagRatio: { ...num, minimum: 0 },
              events: array({ $ref: "#/definitions/event" }, 1, 2000),
            },
            ["type", "events"],
          ),
        ),
      ],
    },
  },
};

/** @deprecated Use supportedEvents. */
export const supportedAnimations = supportedEvents;
